// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDzkykdvJwgE-7nyYnASO8JHVbjTl4sio',
    appId: '1:422065753110:web:3c168f9befcaf31d51b937',
    messagingSenderId: '422065753110',
    projectId: 'investorapp-4de71',
    authDomain: 'investorapp-4de71.firebaseapp.com',
    storageBucket: 'investorapp-4de71.firebasestorage.app',
    measurementId: 'G-DR4YGZ1DKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF3tGRxLrFIMrrHkx1qVbmFoz6UaR8v6g',
    appId: '1:422065753110:android:14d91f96d588b1ec51b937',
    messagingSenderId: '422065753110',
    projectId: 'investorapp-4de71',
    storageBucket: 'investorapp-4de71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALEd1fHEU8_tvX0iwCT37xYCZNbfqKJ58',
    appId: '1:422065753110:ios:d373350c00090f0b51b937',
    messagingSenderId: '422065753110',
    projectId: 'investorapp-4de71',
    storageBucket: 'investorapp-4de71.firebasestorage.app',
    iosBundleId: 'com.example.investorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALEd1fHEU8_tvX0iwCT37xYCZNbfqKJ58',
    appId: '1:422065753110:ios:d373350c00090f0b51b937',
    messagingSenderId: '422065753110',
    projectId: 'investorapp-4de71',
    storageBucket: 'investorapp-4de71.firebasestorage.app',
    iosBundleId: 'com.example.investorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDzkykdvJwgE-7nyYnASO8JHVbjTl4sio',
    appId: '1:422065753110:web:284e397f2310e89a51b937',
    messagingSenderId: '422065753110',
    projectId: 'investorapp-4de71',
    authDomain: 'investorapp-4de71.firebaseapp.com',
    storageBucket: 'investorapp-4de71.firebasestorage.app',
    measurementId: 'G-GZ73RB6VKW',
  );

}